"""Initial schema

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.database.base import UTCInstant
from app.database.types import Guid

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_generation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permissions",
        sa.Column("id", Guid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", UTCInstant(), nullable=False),
        sa.Column("updated_at", UTCInstant(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "roles",
        sa.Column("id", Guid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCInstant(), nullable=False),
        sa.Column("updated_at", UTCInstant(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", Guid(), nullable=False),
        sa.Column("permission_id", Guid(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_index(
        op.f("ix_role_permissions_permission_id"),
        "role_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", Guid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", Guid(), nullable=False),
        sa.Column("deleted_at", UTCInstant(), nullable=True),
        sa.Column("created_at", UTCInstant(), nullable=False),
        sa.Column("updated_at", UTCInstant(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.create_table(
        "activity_logs",
        sa.Column("id", Guid(), nullable=False),
        sa.Column("user_id", Guid(), nullable=True),
        sa.Column("actor_id_snapshot", Guid(), nullable=True),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("behavior", sa.String(length=64), nullable=False),
        sa.Column("entity_id", Guid(), nullable=True),
        sa.Column("endpoint_id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("before", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("after", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", UTCInstant(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_actor_time", "activity_logs", ["user_id", "created_at"], unique=False)
    op.create_index("ix_audit_created", "activity_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_endpoint_time", "activity_logs", ["endpoint_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_entity_time", "activity_logs", ["module", "entity_id", "created_at"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", Guid(), nullable=False),
        sa.Column("recipient_id", Guid(), nullable=False),
        sa.Column("actor_id", Guid(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column("email_status", sa.String(length=16), nullable=False),
        sa.Column("read_at", UTCInstant(), nullable=True),
        sa.Column("created_at", UTCInstant(), nullable=False),
        sa.CheckConstraint(
            "email_status IN ('NOT_REQUESTED','PENDING','SENT','FAILED')",
            name="ck_notification_email_status",
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_recipient_time",
        "notifications",
        ["recipient_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", Guid(), nullable=False),
        sa.Column(
            "token_hash",
            sa.String(length=64, collation="utf8mb4_bin").with_variant(
                sa.String(length=64), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("family_id", Guid(), nullable=False),
        sa.Column("user_id", Guid(), nullable=False),
        sa.Column("expires_at", UTCInstant(), nullable=False),
        sa.Column("revoked_at", UTCInstant(), nullable=True),
        sa.Column("created_at", UTCInstant(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        "ix_refresh_user_expiry", "refresh_tokens", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "stored_files",
        sa.Column("id", Guid(), nullable=False),
        sa.Column("storage", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "object_key",
            sa.String(length=255, collation="utf8mb4_bin").with_variant(
                sa.String(length=255), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("uploader_id", Guid(), nullable=True),
        sa.Column("created_at", UTCInstant(), nullable=False),
        sa.ForeignKeyConstraint(["uploader_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index("ix_file_created", "stored_files", ["created_at"], unique=False)
    op.create_index(
        "ix_file_uploader_created", "stored_files", ["uploader_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_file_uploader_created", table_name="stored_files")
    op.drop_index("ix_file_created", table_name="stored_files")
    op.drop_table("stored_files")
    op.drop_index("ix_refresh_user_expiry", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_notification_recipient_time", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_audit_entity_time", table_name="activity_logs")
    op.drop_index("ix_audit_endpoint_time", table_name="activity_logs")
    op.drop_index("ix_audit_created", table_name="activity_logs")
    op.drop_index("ix_audit_actor_time", table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_role_permissions_permission_id"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("cache_generation")
    # ### end Alembic commands ###
